const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Store}=require('./store');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pos-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const s=new Store(path.join(dir,'pos.json'));const supplier=s.master('suppliers',{name:'テスト商店'});const p=s.master('products',{name:'テスト商品',barcode:'500',shortcut:'1',salePrice:100,costPrice:50,taxType:'内税',taxRate:10,supplierId:String(supplier.id)});return {s,p};}
test('100円内税10%の観測例・釣銭・取引時点の保存',t=>{const {s,p}=fixture(t);const tx=s.transact({requestId:'sale',mode:'販売',lines:[{productId:p.id,quantity:1,price:100}],tender:200});assert.equal(tx.total,100);assert.equal(tx.lines[0].tax,9);assert.equal(tx.change,100);s.master('products',{...p,name:'変更後',salePrice:300});const reopened=new Store(s.file);assert.equal(reopened.db.transactions[0].lines[0].name,'テスト商品');assert.equal(reopened.db.products[0].salePrice,300);});
test('二重確定は同じ記録を返す',t=>{const {s,p}=fixture(t);const input={requestId:'same',mode:'販売',lines:[{productId:p.id,quantity:1,price:100}],tender:100};assert.equal(s.transact(input).id,s.transact(input).id);assert.equal(s.db.transactions.length,1);});
test('不正入力・預かり不足・未実装確定では保存しない',t=>{const {s,p}=fixture(t);for(const extra of [{quantity:-1},{quantity:1.5},{price:NaN},{discount:101},{productId:999}])assert.throws(()=>s.transact({requestId:JSON.stringify(extra),mode:'販売',lines:[{productId:p.id,quantity:1,price:100,...extra}],tender:100}));assert.throws(()=>s.transact({requestId:'short',mode:'販売',lines:[{productId:p.id,quantity:1,price:100}],tender:99}));assert.throws(()=>s.transact({requestId:'credit',mode:'掛売',lines:[{productId:p.id,quantity:1,price:100}]}));assert.equal(s.db.transactions.length,0);});
test('仕入50円と棚卸0個を記録しマスタの在庫を変更しない',t=>{const {s,p}=fixture(t);assert.equal(s.transact({requestId:'buy',mode:'現金仕入',lines:[{productId:p.id,quantity:1,price:50}]}).total,50);assert.equal(s.transact({requestId:'count',mode:'棚卸',lines:[{productId:p.id,quantity:0,price:100}]}).total,0);assert.deepEqual(s.db.products[0],p);});
test('商品識別キー必須・重複・価格不正',t=>{const {s,p}=fixture(t);assert.throws(()=>s.master('products',{...p,id:undefined}));assert.throws(()=>s.master('products',{...p,id:undefined,barcode:'',shortcut:''}));assert.throws(()=>s.master('products',{...p,salePrice:-1}));});
test('顧客・仕入先・設定・入出金を再読込できる',t=>{const {s}=fixture(t);s.master('customers',{name:'顧客A',cardId:'000003'});s.settings({operator:'父',weather:'晴れ'});s.transact({requestId:'cash',mode:'入金',amount:1000,note:'釣銭準備'});assert.throws(()=>s.transact({requestId:'badcash',mode:'出金',amount:-100,note:'不正'}));const reopened=new Store(s.file);assert.equal(reopened.db.customers[0].cardId,'000003');assert.equal(reopened.db.suppliers[0].name,'テスト商店');assert.equal(reopened.db.settings.operator,'父');assert.equal(reopened.db.transactions[0].total,1000);});
test('未確認モードの仮伝票は取引や在庫に影響せず二重保存を防ぐ',t=>{const {s,p}=fixture(t);const before=structuredClone(s.db.products);const draft={requestId:'draft',mode:'掛売',lines:[{productId:p.id,quantity:2,price:100}]};assert.equal(s.draft(draft).id,s.draft(draft).id);assert.equal(s.db.transactions.length,0);assert.equal(s.db.drafts.length,1);assert.deepEqual(s.db.products,before);assert.equal(new Store(s.file).db.drafts[0].mode,'掛売');assert.throws(()=>s.draft({...draft,requestId:'invalid',mode:'販売'}));});
test('仕入先・店舗別仕入履歴・棚卸明細重複を検証する',t=>{const {s,p}=fixture(t);s.master('products',{...p,supplierId:''});assert.throws(()=>s.transact({requestId:'missing',mode:'現金仕入',lines:[{productId:p.id,quantity:1,price:50}]}));s.master('products',p);assert.throws(()=>s.transact({requestId:'no-buy',mode:'棚卸',lines:[{productId:p.id,quantity:1,price:100}]}));s.transact({requestId:'buy',mode:'現金仕入',lines:[{productId:p.id,quantity:1,price:50}]});assert.throws(()=>s.quote('棚卸',[{productId:p.id,quantity:1,price:100},{productId:p.id,quantity:2,price:100}]));s.settings({shopNumber:2});assert.throws(()=>s.transact({requestId:'other-shop',mode:'棚卸',lines:[{productId:p.id,quantity:1,price:100}]}));});
test('空値・真偽値・顧客ID重複・未実装掛売入金を拒否する',t=>{const {s,p}=fixture(t);for(const quantity of ['',true,null])assert.throws(()=>s.quote('販売',[{productId:p.id,quantity,price:100}]));s.master('customers',{name:'A',cardId:'000003'});assert.throws(()=>s.master('customers',{name:'B',cardId:'000003'}));assert.throws(()=>s.transact({requestId:'creditcash',mode:'入金',cashType:'顧客掛売入金',amount:100,note:'test'}));});
test('設定保存は他のタブの設定を失わずバックアップを残す',t=>{const {s}=fixture(t);s.settings({mergeSame:false,cards:['VISA試作']});s.settings({operator:'担当'});const reopened=new Store(s.file);assert.equal(reopened.db.settings.mergeSame,false);assert.deepEqual(reopened.db.settings.cards,['VISA試作']);assert.equal(reopened.db.settings.operator,'担当');assert.ok(fs.existsSync(s.file+'.bak'));assert.throws(()=>s.settings({shopNumber:0}));});
